### ISSUE TITLE
01A and 27hc641

### ISSUE THREAD

**Issue by Maurotb** [schlae/EMP-20Module#6]
Hi,
When i program 27hc641 with module 01A, emp-20 skip write FF (it assume is blank and skip write yo speedup?) And eprom not work. 27hc641 have a random value after blank it (is three state eprom) and need to write FF too. Can you have find this problem? Thanks

**Comment by schlae** [comment]
like you mentioned the 27hc641 (according to the datasheet i found) bit cells are in an undefined state after being erased, unlike most other devices i've used. it seems that it must be programmed explicitly with a 1 or a 0, so skipping cells is definitely not right. maybe the emp-20 algorithm is bugged or was never tested with this device? i'm not sure and i don't have a way to fix it or even test it since i don't have any of those chips. sorry i can't help.
